### ISSUE TITLE
Bring back map/fold/reduce functions on Seq

### ISSUE THREAD

**Issue by devboy** [wooga/Wooga.Lambda-CSharp#18]
After sleeping over this, I now strongly disagree with taking the naming of linq. 

Wooga.Lambda is about functional concepts and heavily inspired by other languages / frameworks.

We already use map/bind/then etc. for Monads (either/maybe/async). 

All the literature talks about fold/map/reduce so we should stick with that too.

See:
http://fsharpforfunandprofit.com/posts/elevated-world/
http://underscorejs.org/
https://msdn.microsoft.com/en-us/library/ee353635.aspx

LINQ is the outlier...

**Comment by flowsprenger** [comment]
LINQ calls it that way because of the LINQ query expression. Anyway, since you explicitly need to use Wooga.Lambda.Data i dont really care personally

**Comment by devboy** [comment]
Yeah, its more database/query verbs than data-structures imho
